# Generated by Django 4.2.16 on 2026-04-05 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120, verbose_name='Mijoz ismi')),
                ('phone_number', models.CharField(max_length=20, verbose_name='Telefon raqami')),
                ('guest_count', models.PositiveSmallIntegerField(verbose_name='Mehmonlar soni')),
                ('reservation_date', models.DateField(db_index=True, verbose_name='Bron sanasi')),
                ('reservation_time', models.TimeField(verbose_name='Bron vaqti')),
                ('seating_preference', models.CharField(choices=[('main_hall', 'Asosiy zal'), ('terrace', 'Terrasa'), ('family_area', 'Oilaviy zona'), ('vip_room', 'VIP xona')], default='main_hall', max_length=20, verbose_name='Joylashuv')),
                ('occasion', models.CharField(choices=[('casual', 'Oddiy tashrif'), ('family_dinner', 'Oilaviy kechki ovqat'), ('business', 'Biznes uchrashuv'), ('birthday', "Tug'ilgan kun"), ('romantic', 'Romantik kecha')], default='casual', max_length=20, verbose_name='Tashrif sababi')),
                ('special_requests', models.TextField(blank=True, verbose_name="Qo'shimcha izoh")),
                ('status', models.CharField(choices=[('pending', 'Kutilmoqda'), ('confirmed', 'Tasdiqlangan'), ('completed', 'Yakunlangan'), ('cancelled', 'Bekor qilingan')], db_index=True, default='pending', max_length=20, verbose_name='Holati')),
                ('is_contacted', models.BooleanField(default=False, verbose_name="Bog'lanildi")),
                ('admin_note', models.TextField(blank=True, verbose_name='Admin eslatmasi')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Yuborilgan vaqt')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Bron',
                'verbose_name_plural': 'Bronlar',
                'ordering': ['reservation_date', 'reservation_time', '-created_at'],
            },
        ),
    ]
